sm8450-common: Enable Dolby Vision and Fix Dolby Atmos Media codecs
sm8450-common: manifest : Include android.hardware.media.c2/dolby

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: Init: Drop setprop ro.media.xml_variant.profiles

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: prop: load media_profiles by system prop

* hardcoded to set correct media_profile

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: sepolicy: Fix dolby vision releated sepolicies

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: prop: Enable dolby vision by vendor prop

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: media: Import stock missing media profiles and vision profiles

*from missi_phone_global-user 14 UKQ1.230804.001 V816.0.7.0.UMRMIXM release-keys

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: fcm: android.hardware.media.c2@1.0::IComponentStore/dolby

ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.media.c2@1.0::IComponentStore/dolby
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 6.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 6 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success
INCOMPATIBLE

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: Build more missing media packages

F  linker  : CANNOT LINK EXECUTABLE "/vendor/bin/modemManager": library "libavservices.so" not found: needed by main executable
F  linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/qcrilNrd": library "libavservices.so" not found: needed by main executable

Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: patch c2.dolby.client blob to load dolby vision

09-25 04:05:32.757  5943  5943 F DEBUG   : Abort message: 'could not dlopen c2.dolby.hevc.dec.so: dlopen failed: cannot locate symbol "_ZN7android8hardware5media2c24V1_05utils6objcpyEPNS3_10WorkBundleERKNSt3__14listINS7_10unique_ptrI6C2WorkNS7_14default_deleteISA_EEEENS7_9allocatorISD_EEEEPNS4_16BufferPoolSenderE" referenced by "/vendor/lib64/c2.dolby.client.so"...'
09-25 04:04:22.149  3380  3380 F DEBUG   : Abort message: 'could not dlopen c2.dolby.hevc.dec.so: dlopen failed: cannot locate symbol "_ZN7android8hardware5media2c24V1_05utils6objcpyEPNS3_10WorkBundleERKNSt3__14listINS7_10unique_ptrI6C2WorkNS7_14default_deleteISA_EEEENS7_9allocatorISD_EEEEPNS4_16BufferPoolSenderE" referenced by "/vendor/lib64/c2.dolby.client.so"...'

Change-Id: I2034f55a1b6d02d267363965d5a941cd587ac9e2
Signed-off-by: kenway214 <kenway214@outlook.com>

sm8450-common: Dolby: fixup dolby mediacodecs support

Signed-off-by: kenway214 <kenway214@outlook.com>